name: math_demo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/


flutter_native_splash:
  android: true
  ios: true

  color: "#FFBC00"
  image: assets/images/logo/logo1.png

  branding: assets/text/text4.png

  android_12:
    color: "#FFBC00"
    image: assets/images/logo/logo1.png
    branding: assets/text/text4.png


  fullscreen: true
