name: math_demo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/login_parts/parts/al_lok_dal_lok.png
    - assets/images/login_parts/parts/love.png
    - assets/images/login_parts/parts/math.png
    - assets/images/login_parts/parts/palette.png
    - assets/images/login_parts/parts/star.png
    - assets/images/login_parts/parts/watermelon.png
    - assets/images/login_parts/parts/wizard.png
    - assets/logo/logo12.png
    - assets/image2/loginimage.png


flutter_native_splash:
  android: true
  ios: true

  color: "#FFFFFF"
  image: assets/logo/logo12.png



  android_12:
    color: "#FFFFFF"
    image: assets/logo/logo12.png



  fullscreen: true
